### ISSUE TITLE
Support configuring several players

### ISSUE THREAD

**Issue by mdosch** [raitonoberu/sptlrx#63]
Thank you very much for this helpful program.

It seems that it's not possible to configure several players, e.g.:

```
# config.yaml    
player: mpris    
mpris:    
  players: [cmus]    
    
player: mpd    
mpd:    
  address: 127.0.0.1:6600    
```

This will only work with mpd but not cmus. Would it be feasible to range over several configured players and use the first one that is currently playing?
