### ISSUE TITLE
v2: feature proposals

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/sptlrx#64]
Originally sptlrx was designed to only support Spotify, but was quickly updated with many other features. And the current Spotify-centric design makes it difficult to implement new features. I want to start from scratch.

In this issue, I'll be keeping a *wishlist* of features/ideas for sptlrx v2, which will eventually turn into a to-do list. You guys are welcome to discuss or add anything too :)

- Multi-player (#40, #63). Iterate through enabled players and select the one that currently has something playing. Prioritization.
- Multi-source (#40). Iterate through the sources and select the one with the timesynced lyric. Prioritization.
- Improve local source. Attempt to find `.lrc` file on track path (#53). Attempt to extract embedded lyric.
- “No text” placeholder (#55). Make it optional.
- Remove support for [lyricsapi](https://github.com/raitonoberu/lyricsapi). This has just been a fancy proxy to lrclib for a long time. So replace it with plain lrclib (+optional search logic described [here](https://github.com/raitonoberu/sptlrx/issues/48#issue-2314558219)).
- Improved `.lrc` file parser (#51). We may find some tags useful!
- Spotify authentication via API (#56). The current implementation was made with using the internal API to retrieve song lyrics directly from Spotify in mind. However, there are now other ways to retrieve song lyrics that work just as well. Take advantage of them and use the public API just to get the title and position. May require a lot of work, so probably won't be in 2.0.
- Support for nscpot (#38). Again, a lot of work for a potentially small number of users, so only if this gets enough votes.
- TOML config. The config structure is going to change a lot anyway, and I feel the `yaml` format is not flexible/convenient enough. Migration command.
- Sensible defaults. Now we show text on how to set up Spotify cookies on first run. Instead let's default to `lrclib` & `mpris` (unfortunately only for linux).
- Logging (#45). In its current state (`ignoreErrors` flag) it's just awful. Just write it somewhere, it won't hurt anyone.
- Test coverage... No comments here.

**Comment by raitonoberu** [comment]
This is how pretty our `.toml` config would look. Any thoughts?

<details>

```toml
[style]
align = "center"

[style.current]
foreground = 0xffc0cb

[players.spotify]
enabled = true
cookie = "qwerty"
priority = 1

[players.mpris]
enabled = true
whitelist = ["rhythmbox", "firefox"]
priority = 0

[source.spotify]
enabled = true
priority = 2

[sources.local]
enabled = true
directory = "~/Music"
priority = 1

[sources.lrclib]
enabled = true
priority = 0

[logging]
enabled = true
file = "/tmp/sptlrx.log"
```
</details>
